### ISSUE TITLE
패키지 구조

### ISSUE THREAD

**Issue by techhan** [TOO-IT/Tooit-backend#1]
저희 패키지 구조는 계층형 vs 도메인형 중에 어떤 거로 진행할까요?

참고 : https://velog.io/@jsb100800/Spring-boot-directory-package

**Comment by jhnyuk** [comment]
안녕하세요 ! 혹시 사용하시던 패키지 구조가 있으실까요?
저는 기존에 예를 들어 usr 폴더에 Entity, Service, Reposiroty, Controller, config, util 등으로 나눠 도메인형 디렉터리 구조를 사용해왔습니다.
계층형은 한 폴더에서 파일을 찾기 어려울 수도 있으니.. 도메인형이 더 나을 수도 있다는 생각입니다 ㅎㅎ

**Comment by techhan** [comment]
저도 도메인형으로 사용해봤던 거 같아요!
그럼 도메인형으로 가시죠!!👌🏼

**Comment by jhnyuk** [comment]
좋습니다 ! 도메인형 패키지 구조로 구성하는 것으로 알겠습니다 😊
