### ISSUE TITLE
양방향 연관관계

### ISSUE THREAD

**Issue by techhan** [TOO-IT/Tooit-backend#4]
양방향 연관관계는 되도록 맺지 않는 것이 좋고, 일단 단방향으로 맺은 다음에 양방향 연관관계가 필요시 추가하면 된다고 모든 블로그에서 입 모아 말하길래 일단 단방향 연관관계로 다 맺어 놓았습니다만..!
저희 도메인 중에 양방향 연관관계를 맺어야 할 도메인들이 있을까요? 

레퍼런스 : https://bcp0109.tistory.com/331

**Comment by jhnyuk** [comment]
네 ! 확인해보니 단방향으로 연관관계로 충분히 맺어져 있는 것 같습니다 그래서 양방향 연관관계를 맺어야 할 도메인은 아직 없는 것 같습니다.
추후에 Review 엔티티와 Vote, User 엔티티와의 단방향 연관관계를 맺을 수 있도록 하는 건 어떨까요 ?!
- vote 엔티티에 user 추가, voteItem 엔티티에 vote 추가, Review 엔티티에 user, vote 추가 하는 등 ..?

**Comment by techhan** [comment]
넵 그럼 추후에 개발하면서 추가하도록 해봅시다!
