### ISSUE TITLE
프론트엔드 분들 api 테스트 방법

### ISSUE THREAD

**Issue by techhan** [TOO-IT/Tooit-backend#5]
프론트분들이 서버쪽에서 작성된 api 테스트할 때 어떤 방식으로 해야하냐고 물어보셨는데..! 
어떤 방식으로 테스트를 제공해드려야할까요? 저희가 git 저장소가 나뉘어져있다보니 어떤 방식으로 해야할지 감이 안잡힙니다!
혹시 git 저장소가 분리되어 있는 환경에서 개발 해보셨나요?!

**Comment by jhnyuk** [comment]
아니요 git 저장소가 분리되어 있는 환경에서 개발해본 적은 없는데 ,, swagger나 postman로 테스트 하거나 또는 더미데이터를 만들어서 전달해드리면 될 것 같습니다 !

**Comment by techhan** [comment]
그러면 프론트 분들에게 백엔드 쪽 git pull 받으시고 서버 실행하셔서 테스트 한다고 전달해드리면 될까요?!

**Comment by jhnyuk** [comment]
git pull 받아서 하시면 데이터베이스도 설치랑 세팅도 하셔야 해서 복잡할 수 있을 것 같네요 ..! 저희 swagger 사용하니까 이거 사용하셔서 api 테스트 하면 된다고 전달해드리면 될 것 같아요 !
아직 api 개발이 안 됐으니까 직접 Swagger UI를 사용해서 모의 API 생성하고 테스트하셔야 할 것 같습니다 ..

**Comment by techhan** [comment]
근데 또 swagger도 localhost:8080/~로 시작해서 어쨌든 서버를 실행하긴 해야하는데.. pull 받고 서버 실행 후 swagger 주소로 들어가셔서 보시면 될 거 같다고 말씀드리면 될까요?!

**Comment by jhnyuk** [comment]
네넵 좋습니다 !
