### ISSUE TITLE
SNS 회원가입

### ISSUE THREAD

**Issue by techhan** [TOO-IT/Tooit-backend#6]
SNS 회원가입 구현에 대해 찾아보니 
일반적인 OAuth2로 구현하는 방식과 JWT + OAuth2로 구현하는 방식이 있는데
저희는 둘 중에 어떤 방식으로 진행하면 좋을까요?

**Comment by jhnyuk** [comment]
OAuth2만 사용한다면 스프링 시큐리티 이용해서 하면 되니까 토큰 사용해서 하는 것보다 간단하긴 합니다 ! REST API로 할 예정이면 어렵지만 JWT + OAuth2로 하는 방식이 좋을 것 같아요 !

**Comment by techhan** [comment]
오 그럼 프론트 분들에게 JWT + OAuth2 방식으로 한다고 전달드리겠습니다!
